name: Node.js CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      rabbitmq:
        image: rabbitmq:3.9-alpine
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run test
        run: npm test
        env:
          TADASHI_AMQP_URL: amqp://127.0.0.1:5672
          TADASHI_AMQP_QUEUE: test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
